"""Contract tests for the package-owned public API quality audit."""

from __future__ import annotations

import ast
from pathlib import Path

PACKAGE_ROOT = Path(__file__).parents[1] / "src" / "dj_hyperview"
_DEFINITION = (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)
_DOCUMENTABLE = (ast.Module, *_DEFINITION)


def _diagnostic(path: str, node: ast.AST, symbol: str, reason: str) -> str:
    return f"{path}:{getattr(node, 'lineno', 1)}:{symbol}: {reason}"


def _exports(tree: ast.Module) -> set[str]:
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(
            isinstance(target, ast.Name) and target.id == "__all__"
            for target in node.targets
        ):
            try:
                value = ast.literal_eval(node.value)
            except (ValueError, TypeError):
                return set()
            if isinstance(value, (list, tuple)) and all(
                isinstance(item, str) for item in value
            ):
                return set(value)
    return set()


def _is_public(name: str, exports: set[str]) -> bool:
    return not name.startswith("_") or name in exports


def _ordered(issues: list[str]) -> list[str]:
    def key(issue: str) -> tuple[str, int, str]:
        path, line, detail = issue.split(":", 2)
        return path, int(line), detail

    return sorted(issues, key=key)


def _audit_text(source: str, path: str = "sample.py") -> list[str]:
    tree = ast.parse(source, filename=path)
    issues: list[str] = []
    exports = _exports(tree)
    if ast.get_docstring(tree) is None:
        issues.append(
            _diagnostic(path, tree, "<module>", "runtime module lacks a docstring")
        )

    for node in ast.walk(tree):
        if isinstance(node, _DOCUMENTABLE):
            docstring = ast.get_docstring(node)
            if docstring and "`" in docstring:
                symbol = getattr(node, "name", "<module>")
                issues.append(
                    _diagnostic(path, node, symbol, "docstring uses backticks")
                )

    for node in tree.body:
        if not isinstance(node, _DEFINITION) or not _is_public(node.name, exports):
            continue
        if ast.get_docstring(node) is None:
            kind = "class" if isinstance(node, ast.ClassDef) else "callable"
            issues.append(
                _diagnostic(path, node, node.name, f"public {kind} lacks a docstring")
            )
        if isinstance(node, ast.ClassDef):
            for method in node.body:
                if (
                    isinstance(method, (ast.FunctionDef, ast.AsyncFunctionDef))
                    and not method.name.startswith("_")
                    and ast.get_docstring(method) is None
                ):
                    issues.append(
                        _diagnostic(
                            path,
                            method,
                            f"{node.name}.{method.name}",
                            "public method lacks a docstring",
                        )
                    )
    return _ordered(issues)


def _audit_package() -> list[str]:
    issues: list[str] = []
    for path in sorted(PACKAGE_ROOT.rglob("*.py")):
        source = path.read_text(encoding="utf-8")
        if "migrations" in path.parts or source.lstrip().startswith("# Generated by"):
            continue
        relative = path.relative_to(PACKAGE_ROOT.parent.parent).as_posix()
        issues.extend(_audit_text(source, relative))
    return _ordered(issues)


def test_public_api_docstrings_have_no_debt_or_allowlist() -> None:
    """Require documented public symbols and backtick-free package docstrings."""
    assert _audit_package() == []


def test_auditor_reports_deterministic_docstring_failures() -> None:
    """Prove all public symbol levels and private backticks are diagnosed."""
    source = '''class Public:
    def run(self):
        pass

def exposed():
    pass

def documented():
    """Uses `public` syntax."""

def _private():
    """Uses `private` syntax."""
'''
    assert _audit_text(source) == [
        "sample.py:1:<module>: runtime module lacks a docstring",
        "sample.py:1:Public: public class lacks a docstring",
        "sample.py:2:Public.run: public method lacks a docstring",
        "sample.py:5:exposed: public callable lacks a docstring",
        "sample.py:8:documented: docstring uses backticks",
        "sample.py:11:_private: docstring uses backticks",
    ]


def test_auditor_honors_exports_without_requiring_private_symbols() -> None:
    """Prove explicit exports are public while ordinary private names remain private."""
    source = '''"""Documented module."""
__all__ = ["_exported"]

def _exported():
    pass

def _internal():
    pass
'''
    assert _audit_text(source) == [
        "sample.py:4:_exported: public callable lacks a docstring"
    ]
